// CONFIG SCHEMA
// Maps each known setting key to its UI control type and section.
const SCHEMA = {
  // General
  g_fCursorSpeed:          { type: 'range', min: 0.1, max: 5, step: 0.1, section: 'General' },
  g_bMFDHighContrast:      { type: 'toggle', section: 'General' },
  g_fRadarScale:           { type: 'range', min: 0.1, max: 2, step: 0.05, section: 'General' },
  g_bHSD_HAD_FCR_Font:     { type: 'toggle', section: 'General' },
  g_fHADSymbolSize:        { type: 'number', section: 'General' },
  g_fHSDSymbolSize:        { type: 'number', section: 'General' },
  g_bBarcapNoBarcap:       { type: 'toggle', section: 'General' },
  g_bNoDTCForRampStart:    { type: 'toggle', section: 'General' },
  g_nPrintToFile:          { type: 'toggle', section: 'General' },
  g_bAppendToBriefingFile: { type: 'toggle', section: 'General' },
  g_bBriefHTML:            { type: 'toggle', section: 'General' },
  g_bLogEvents:            { type: 'toggle', section: 'General' },
  g_bEnableDisplacementCam: { type: 'toggle', section: 'General' },
  g_b3DClickableCursorAnchored: { type: 'toggle', section: 'General' },
  g_fDefaultFOV:           { type: 'range', min: 20, max: 120, step: 1, section: 'General' },
  g_bFullScreenNVG:        { type: 'toggle', section: 'General' },
  g_bNoPadlockBoxes:       { type: 'toggle', section: 'General' },
  g_bPngScreenshots:       { type: 'toggle', section: 'General' },
  g_nPadlockBoxSize:       { type: 'range', min: 1, max: 5, step: 1, section: 'General' },
  g_bPlayIntroMovie:       { type: 'toggle', section: 'General' },
  g_bRampTaxiStart:        { type: 'toggle', section: 'General' },
  g_bCalibrationHg:        { type: 'toggle', section: 'General' },

  // Graphics
  g_bHiResTextures:        { type: 'toggle', section: 'Graphics' },
  g_bEnvironmentMapping:   { type: 'toggle', section: 'Graphics' },
  g_bHdrLighting:          { type: 'toggle', section: 'Graphics' },
  g_bHdrLightingStar:      { type: 'toggle', section: 'Graphics' },
  g_bUseHeatHazeShader:    { type: 'toggle', section: 'Graphics' },
  g_bShowFarRain:          { type: 'toggle', section: 'Graphics' },
  g_bShowRainDrops:        { type: 'toggle', section: 'Graphics' },
  g_bShowRainRings:        { type: 'toggle', section: 'Graphics' },
  g_bShadowMapping:        { type: 'toggle', section: 'Graphics' },
  g_bShadowOnSmoke:        { type: 'toggle', section: 'Graphics' },
  g_bWaterEnvironmentMapping: { type: 'toggle', section: 'Graphics' },
  g_bEnvMapRenderClouds:   { type: 'toggle', section: 'Graphics' },
  g_bEnvMapRenderFocusObject: { type: 'toggle', section: 'Graphics' },
  g_bReducePSFires:        { type: 'toggle', section: 'Graphics' },
  g_nAnisotropicValue:     { type: 'select', options: [['0','Max available'],['2','2x'],['4','4x'],['8','8x'],['16','16x']], section: 'Graphics' },
  g_fSmartScalingThreshold: { type: 'number', section: 'Graphics' },
  g_fAmbientmin:           { type: 'range', min: 0, max: 0.5, step: 0.01, section: 'Graphics' },

  // Terrain
  g_bEnableNewTerrain:     { type: 'toggle', section: 'Terrain' },
  g_bNewTerrainRenderShrubs: { type: 'toggle', section: 'Terrain' },
  g_bNewTerrainRenderGrass: { type: 'toggle', section: 'Terrain' },
  g_fNewTerrainProceduralDistance: { type: 'range', min: 1, max: 30, step: 0.5, section: 'Terrain' },
  g_nNewTerrainHiresTilesDistKM: { type: 'select', options: [['0','Disabled'],['16','16 km'],['32','32 km']], section: 'Terrain' },
  g_fNewTerrainCoarseBumpMapIntensity: { type: 'range', min: 0, max: 1, step: 0.025, section: 'Terrain' },
  g_nNewTerrainCoarseBumpMapTilingCx: { type: 'range', min: 1, max: 64, step: 1, section: 'Terrain' },

  // VR
  g_nVRHMD:                { type: 'select', options: [['0','Disabled'],['1','SteamVR'],['2','OpenXR']], section: 'VR' },
  g_fVRZoom:               { type: 'range', min: 1, max: 4, step: 0.1, section: 'VR' },
  g_nVRHMCSEYE:            { type: 'select', options: [['-1','Both'],['0','Right'],['1','Left']], section: 'VR' },
  g_nVRExternalRenderingMode: { type: 'select', options: [['0','Mixed'],['1','Always mono'],['2','Always stereo']], section: 'VR' },
  g_fVRAltitudeFeetToRenderMono: { type: 'range', min: 0, max: 500, step: 5, section: 'VR' },
  g_fVRResolution:         { type: 'range', min: 0.5, max: 2.0, step: 0.05, section: 'VR' },
  g_fVRIPDMultiplier:      { type: 'range', min: 0.5, max: 2.0, step: 0.05, section: 'VR' },
  g_bVRParallelRenderThread: { type: 'toggle', section: 'VR' },
  g_bVRPredictFutureHeadMatrices: { type: 'toggle', section: 'VR' },
  g_bVRNoPresent:          { type: 'toggle', section: 'VR' },
  g_bMixedRealityCockpitCoverEnabled: { type: 'toggle', section: 'VR' },
  g_b3DClickableCursorFixToCenterIfVR: { type: 'toggle', section: 'VR' },

  // Sound
  g_nDynamicVoices:        { type: 'range', min: 8, max: 256, step: 8, section: 'Sound' },
  g_nSoundUpdateMS:        { type: 'range', min: 5, max: 50, step: 1, section: 'Sound' },
  g_nSoundSwitchFix:       { type: 'toggle', section: 'Sound' },
  g_fRadioBalance:         { type: 'range', min: -10, max: 10, step: 0.5, section: 'Sound' },
  g_nIvcUiVolume:          { type: 'range', min: -6, max: 6, step: 1, section: 'Sound' },
  g_bUseIvcUiVolume:       { type: 'toggle', section: 'Sound' },

  // TTS & Radio
  g_bEnableTTS:            { type: 'toggle', section: 'TTS & Radio' },
  g_nTTSSpeedAdjust:       { type: 'range', min: -10, max: 10, step: 1, section: 'TTS & Radio' },
  g_bDisableCommsMenu:     { type: 'toggle', section: 'TTS & Radio' },
  g_nRadioMenuAlpha:       { type: 'range', min: 0, max: 100, step: 5, section: 'TTS & Radio' },
  g_nMaxBRAARange:         { type: 'range', min: 5, max: 100, step: 5, section: 'TTS & Radio' },
  g_bInitBUPfromDTC:       { type: 'toggle', section: 'TTS & Radio' },
  g_nF1TeamUiFreq:         { type: 'number', section: 'TTS & Radio' },
  g_nF2TeamUiFreq:         { type: 'number', section: 'TTS & Radio' },

  // HOTAS & Input
  g_nHotasPinkyShiftMagnitude: { type: 'range', min: 0, max: 512, step: 8, section: 'HOTAS & Input' },
  g_fMouseSensitivity:     { type: 'range', min: 0.1, max: 5, step: 0.1, section: 'HOTAS & Input' },
  g_bMouseWheelKnobs:      { type: 'toggle', section: 'HOTAS & Input' },
  g_bEnableExclusiveMouseCapture: { type: 'toggle', section: 'HOTAS & Input' },
  g_bMouseButton4TogglesClickablePit: { type: 'toggle', section: 'HOTAS & Input' },
  g_fFOVIncrement:         { type: 'range', min: 1, max: 20, step: 1, section: 'HOTAS & Input' },
  g_fMaximumFOV:           { type: 'range', min: 60, max: 180, step: 5, section: 'HOTAS & Input' },
  g_fNarrowFOV:            { type: 'range', min: 5, max: 45, step: 1, section: 'HOTAS & Input' },
  g_bAfterburnerDetentClick: { type: 'toggle', section: 'HOTAS & Input' },
  g_bHotasDgftSelfCancel:  { type: 'toggle', section: 'HOTAS & Input' },
  g_bUseVirtualRudder:     { type: 'toggle', section: 'HOTAS & Input' },
  g_bUseAnalogIdleCutoff:  { type: 'toggle', section: 'HOTAS & Input' },

  // Multiplayer
  g_bAllowMP_Freeze:       { type: 'toggle', section: 'Multiplayer' },
  g_bAllowMP_NVG:          { type: 'toggle', section: 'Multiplayer' },
  g_bAllowMP_NVGFullscreen: { type: 'toggle', section: 'Multiplayer' },
  g_bRequireSameAcdataMP:  { type: 'toggle', section: 'Multiplayer' },
  g_bRequireSameTileSetMP: { type: 'toggle', section: 'Multiplayer' },
  g_bAllowMP_Smoke:        { type: 'toggle', section: 'Multiplayer' },
  g_nMPStartRestricted:    { type: 'toggle', section: 'Multiplayer' },
  g_nTaxiLaunchTime:       { type: 'range', min: 1, max: 30, step: 1, section: 'Multiplayer' },
  g_nReagTimerCamp:        { type: 'range', min: 1, max: 60, step: 1, section: 'Multiplayer' },
  g_nDeagTimerCamp:        { type: 'range', min: 1, max: 60, step: 1, section: 'Multiplayer' },
  g_nReagTimerTE:          { type: 'range', min: 1, max: 120, step: 1, section: 'Multiplayer' },
  g_nDeagTimerTE:          { type: 'range', min: 1, max: 120, step: 1, section: 'Multiplayer' },
  g_nRespawnTimeforStuckAI: { type: 'range', min: 1, max: 30, step: 1, section: 'Multiplayer' },
  g_npercentage_available_aircraft: { type: 'range', min: 10, max: 100, step: 5, section: 'Multiplayer' },
  g_nminimum_available_aircraft: { type: 'range', min: 1, max: 20, step: 1, section: 'Multiplayer' },
  g_bEnableABRelocation:   { type: 'toggle', section: 'Multiplayer' },
  g_nForceMinClientBwSetting: { type: 'number', section: 'Multiplayer' },
  g_nRemoteControlSurfacesInterval: { type: 'range', min: 20, max: 1000, step: 10, section: 'Multiplayer' },
  g_bEnforceBandwidthLimits: { type: 'toggle', section: 'Multiplayer' },

  // HUD & Display
  g_bShowFrameRateDefault: { type: 'toggle', section: 'HUD & Display' },
  g_bOnlinePlayersDisplayDefault: { type: 'toggle', section: 'HUD & Display' },
  g_bF16MfdHasRwr:         { type: 'toggle', section: 'HUD & Display' },
  g_bhudAOA:               { type: 'toggle', section: 'HUD & Display' },
  g_bNoRPMOnHud:           { type: 'toggle', section: 'HUD & Display' },
  g_nPadlockBoxThickness:  { type: 'range', min: 1, max: 5, step: 1, section: 'HUD & Display' },
  g_fPadlockBoxTimeout:    { type: 'range', min: -1, max: 20, step: 0.5, section: 'HUD & Display' },
  g_fViewlimitPitchDown:   { type: 'range', min: 0, max: 90, step: 1, section: 'HUD & Display' },
  g_nNumberOfSubTitles:    { type: 'range', min: 1, max: 20, step: 1, section: 'HUD & Display' },
  g_nSubTitleTTL:          { type: 'range', min: 1000, max: 30000, step: 500, section: 'HUD & Display' },
  g_fSubtitleWrapWidth:    { type: 'range', min: 0, max: 2, step: 0.05, section: 'HUD & Display' },
  g_nMessageScrollTime:    { type: 'range', min: 3, max: 60, step: 1, section: 'HUD & Display' },
  g_nJpegCompression:      { type: 'range', min: 0, max: 100, step: 5, section: 'HUD & Display' },
  g_bPrettyScreenShot:     { type: 'toggle', section: 'HUD & Display' },
  g_bPreventScreensaver:   { type: 'toggle', section: 'HUD & Display' },
  g_bACMIRecordMsgOff:     { type: 'toggle', section: 'HUD & Display' },
  g_nActionCameraTimer:    { type: 'range', min: 1000, max: 30000, step: 500, section: 'HUD & Display' },

  // Colors
  g_sRadioStandardCol:     { type: 'color', section: 'Colors' },
  g_sRadioTowerCol:        { type: 'color', section: 'Colors' },
  g_sRadioflightCol:       { type: 'color', section: 'Colors' },
  g_sThreatCircleColor_RadarHigh: { type: 'color', section: 'Colors' },
  g_sThreatCircleColor_RadarLow:  { type: 'color', section: 'Colors' },
  g_sThreatCircleColor_ADAHigh:   { type: 'color', section: 'Colors' },
  g_sThreatCircleColor_ADALow:    { type: 'color', section: 'Colors' },
  g_sPPTRingColor:         { type: 'color', section: 'Colors' },
  g_nPPTRingWidth:         { type: 'range', min: 1, max: 5, step: 1, section: 'Colors' },

  // AI & Simulation
  g_bEnableGtraining:      { type: 'toggle', section: 'AI & Simulation' },
  g_bSmartCombatAP:        { type: 'toggle', section: 'AI & Simulation' },
  g_bRealisticMavTime:     { type: 'toggle', section: 'AI & Simulation' },
  g_fMavFOVLevel:          { type: 'range', min: 1, max: 8, step: 0.5, section: 'AI & Simulation' },
  g_fMavEXPLevel:          { type: 'range', min: 1, max: 8, step: 0.5, section: 'AI & Simulation' },
  g_fAIRefuelSpeed:        { type: 'range', min: 0.5, max: 5, step: 0.5, section: 'AI & Simulation' },
  g_bAIGloc:               { type: 'toggle', section: 'AI & Simulation' },
  g_bAIjamLogic:           { type: 'toggle', section: 'AI & Simulation' },
  g_bScramble:             { type: 'toggle', section: 'AI & Simulation' },
  g_bAnyWaypointTask:      { type: 'toggle', section: 'AI & Simulation' },
  g_bEnableRandomFailures: { type: 'toggle', section: 'AI & Simulation' },
  g_fMeanTimeBetweenFailures: { type: 'number', section: 'AI & Simulation' },
  g_bCanopyOpenForRampStarts: { type: 'toggle', section: 'AI & Simulation' },
  g_bEnableWIPF18Avionics: { type: 'toggle', section: 'AI & Simulation' },

  // TrackIR
  g_bExternalTrackIR:      { type: 'toggle', section: 'TrackIR' },
  g_bInvertExternalTrackIR: { type: 'toggle', section: 'TrackIR' },
  g_bExternalTrackIROrientation: { type: 'toggle', section: 'TrackIR' },
  g_nTrackIRTimeout:       { type: 'range', min: 100, max: 5000, step: 100, section: 'TrackIR' },

  // RTT & Export
  g_bExportRTTTextures:    { type: 'toggle', section: 'RTT & Export' },
  g_nRTTExport_FPS:        { type: 'range', min: 1, max: 60, step: 1, section: 'RTT & Export' },

  // Auto Save
  g_nTacPeriodicSaveMinutes:  { type: 'range', min: 0, max: 60, step: 5, section: 'Auto Save' },
  g_nCampPeriodicSaveMinutes: { type: 'range', min: 0, max: 60, step: 5, section: 'Auto Save' },
  g_sCampPeriodicSaveName:    { type: 'text', section: 'Auto Save' },

  // Debug
  g_bLogInputFunctions:    { type: 'toggle', section: 'Debug' },
  g_bActivateDebugStuff:   { type: 'toggle', section: 'Debug' },
  g_nShowDebugLabels:      { type: 'toggle', section: 'Debug' },
  g_bCampLabels:           { type: 'toggle', section: 'Debug' },
  g_bAIprofile:            { type: 'toggle', section: 'Debug' },
  g_bShowMipUsage:         { type: 'toggle', section: 'Debug' },
  g_bLabelShowDistance:    { type: 'toggle', section: 'Debug' },
  g_nNearLabelLimit:       { type: 'range', min: 10, max: 500, step: 10, section: 'Debug' },
  g_bAI_AG_Debug:          { type: 'toggle', section: 'Debug' },
  g_bUsePsTracers:         { type: 'toggle', section: 'Debug' },
  g_bSaveLegacyDb:         { type: 'toggle', section: 'Debug' },
};

const SECTION_COLORS = {
  'General':         '#4a8fd4',
  'Graphics':        '#9b72cf',
  'Terrain':         '#3dba7a',
  'VR':              '#3db8a8',
  'Sound':           '#e8a030',
  'TTS & Radio':     '#e05555',
  'HOTAS & Input':   '#d4537e',
  'Multiplayer':     '#4a8fd4',
  'HUD & Display':   '#639922',
  'Colors':          '#ef9f27',
  'AI & Simulation': '#9b72cf',
  'TrackIR':         '#3db8a8',
  'RTT & Export':    '#4a8fd4',
  'Auto Save':       '#3dba7a',
  'Debug':           '#888780',
};
